In [30]:
#Import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
import seaborn as sns
rcParams['figure.figsize']=10,8

In [31]:
#Load Dataset
dataset = pd.read_csv(r'C:\Python\HousingClean1.csv')
dataset.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  1750000  3620         2          1        1      yes        no       no   
1  1750000  2910         3          1        1       no        no       no   
2  1750000  3850         3          1        2      yes        no       no   
3  1767150  2400         3          1        1       no        no       no   
4  1820000  3000         2          1        1      yes        no      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no              no        0       no      unfurnished  
1              no              no        0       no        furnished  
2              no              no        0       no      unfurnished  
3              no              no        0       no   semi-furnished  
4              no              no        2       no      unfurnished

In [32]:
#Key Statistics
dataset.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.290000e+02    529.000000  529.000000  529.000000  529.000000   
mean   4.592158e+06   5058.610586    2.941399    1.258979    1.788280   
std    1.585562e+06   2076.332676    0.729756    0.463681    0.861956   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3540.000000    2.000000    1.000000    1.000000   
50%    4.270000e+06   4500.000000    3.000000    1.000000    2.000000   
75%    5.600000e+06   6300.000000    3.000000    1.000000    2.000000   
max    9.100000e+06  15600.000000    6.000000    3.000000    4.000000   

          parking  
count  529.000000  
mean     0.663516  
std      0.843992  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [27]:
#View Data Types
dataset.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [33]:
dataset

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    1750000  3620         2          1        1      yes        no       no   
1    1750000  2910         3          1        1       no        no       no   
2    1750000  3850         3          1        2      yes        no       no   
3    1767150  2400         3          1        1       no        no       no   
4    1820000  3000         2          1        1      yes        no      yes   
..       ...   ...       ...        ...      ...      ...       ...      ...   
524  8750000  4320         3          1        2      yes        no      yes   
525  8855000  6420         3          2        2      yes        no       no   
526  8890000  4600         3          2        2      yes       yes       no   
527  8960000  8500         3          2        4      yes        no       no   
528  9100000  6000         4          1        2      yes        no      yes   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no              no        0       no      unfurnished  
1                no              no        0       no        furnished  
2                no              no        0       no      unfurnished  
3                no              no        0       no   semi-furnished  
4                no              no        2       no      unfurnished  
..              ...             ...      ...      ...              ...  
524             yes              no        2       no   semi-furnished  
525              no             yes        1      yes   semi-furnished  
526              no             yes        2       no        furnished  
527              no             yes        2       no        furnished  
528              no              no        2       no   semi-furnished  

[529 rows x 13 columns]

In [37]:
dataset= pd.get_dummies(data=dataset)

In [39]:
dataset

price  area  bedrooms  bathrooms  stories  parking  mainroad_no  \
0    1750000  3620         2          1        1        0            0   
1    1750000  2910         3          1        1        0            1   
2    1750000  3850         3          1        2        0            0   
3    1767150  2400         3          1        1        0            1   
4    1820000  3000         2          1        1        2            0   
..       ...   ...       ...        ...      ...      ...          ...   
524  8750000  4320         3          1        2        2            0   
525  8855000  6420         3          2        2        1            0   
526  8890000  4600         3          2        2        2            0   
527  8960000  8500         3          2        4        2            0   
528  9100000  6000         4          1        2        2            0   

     mainroad_yes  guestroom_no  guestroom_yes  ...  basement_yes  \
0               1             1              0  ...             0   
1               0             1              0  ...             0   
2               1             1              0  ...             0   
3               0             1              0  ...             0   
4               1             1              0  ...             1   
..            ...           ...            ...  ...           ...   
524             1             1              0  ...             1   
525             1             1              0  ...             0   
526             1             0              1  ...             0   
527             1             1              0  ...             0   
528             1             1              0  ...             1   

     hotwaterheating_no  hotwaterheating_yes  airconditioning_no  \
0                     1                    0                   1   
1                     1                    0                   1   
2                     1                    0                   1   
3                     1                    0                   1   
4                     1                    0                   1   
..                  ...                  ...                 ...   
524                   0                    1                   1   
525                   1                    0                   0   
526                   1                    0                   0   
527                   1                    0                   0   
528                   1                    0                   1   

     airconditioning_yes  prefarea_no  prefarea_yes  \
0                      0            1             0   
1                      0            1             0   
2                      0            1             0   
3                      0            1             0   
4                      0            1             0   
..                   ...          ...           ...   
524                    0            1             0   
525                    1            0             1   
526                    1            1             0   
527                    1            1             0   
528                    0            1             0   

     furnishingstatus_furnished  furnishingstatus_semi-furnished  \
0                             0                                0   
1                             1                                0   
2                             0                                0   
3                             0                                1   
4                             0                                0   
..                          ...                              ...   
524                           0                                1   
525                           0                                1   
526                           1                                0   
527                           1                                0   
528                           0                                

In [42]:
#Create x and y variables
x = dataset.drop(['prefarea_yes','prefarea_no'], axis=1).to_numpy()
y = dataset['prefarea_yes'].to_numpy()

#Create Train and Test Datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,stratify=y,random_state = 100) 

#Scale the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [43]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
#Models
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(kernel='linear',random_state=100)),
                    ('Naive Bayes',GaussianNB()),
                   ('LDA', LinearDiscriminantAnalysis()),
                    ('QDA',QuadraticDiscriminantAnalysis()),
                   ('LogReg',LogisticRegression(solver='lbfgs',
                                               class_weight='balanced',
                                               random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['yes','no']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))  


Estimator: SVM
[[83  0]
 [23  0]]
              precision    recall  f1-score   support

         yes       0.78      1.00      0.88        83
          no       0.00      0.00      0.00        23

    accuracy                           0.78       106
   macro avg       0.39      0.50      0.44       106
weighted avg       0.61      0.78      0.69       106


Estimator: Naive Bayes
[[46 37]
 [ 7 16]]
              precision    recall  f1-score   support

         yes       0.87      0.55      0.68        83
          no       0.30      0.70      0.42        23

    accuracy                           0.58       106
   macro avg       0.58      0.62      0.55       106
weighted avg       0.75      0.58      0.62       106


Estimator: LDA
[[83  0]
 [17  6]]
              precision    recall  f1-score   support

         yes       0.83      1.00      0.91        83
          no       1.00      0.26      0.41        23

    accuracy                           0.84       106
   macro avg   

C:\Users\juman\PythonData1200\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juman\PythonData1200\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juman\PythonData1200\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\juman\PythonData1200\lib\site-p